[tool.poetry]
name = "python-concurrency-with-asyncio"
version = "0.1.0"
description = ""
authors = ["Pavel Karateev <lancelote.du.lac@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
