[tool.poetry]
name = "python-concurrency-with-asyncio"
version = "0.1.0"
description = ""
authors = ["Pavel Karateev <lancelote.du.lac@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
mypy = "^0.982"
types-requests = "^2.28.11.2"
ruff = "^0.0.245"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py310']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
exclude = [
    'vendor/',
]
mypy_path = "src"
strict = true

[tool.ruff]
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "vendor"
]
line-length = 80
target-version = "py311"
