name: check

on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: prepare python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install poetry
        run: pip install poetry

      - name: install project dependencies
        run: poetry install

      - name: lint
        run: poetry run pre-commit run --all-files
